// Troubleshooting issues data per refrigerant (EN/AR)
window.ISSUES_DATA = {
  r134a: {
    charging: [
      {title:{en:'Low Charge (Undercharged)',ar:'شحن منخفض (ناقص)'},sym:{en:'Warm vent air, low suction pressure, compressor cycling, ice on suction line',ar:'هواء دافئ من الفتحة، ضغط مصعد منخفض، ضاغط يعمل بشكل متكرر، جليد على خط الشفط'},cause:{en:'Refrigerant leak from hoses, o-rings, evaporator, or condenser',ar:'تسريب مبرد من الخراطيم أو الحلقات O أو المبخر أو المكثف'},fix:{en:'Leak test with UV dye or electronic detector, repair leak, evacuate and recharge to spec by weight',ar:'اختبار تسريب بصبغة UV أو كاشف إلكتروني، إصلاح التسريب، تفريغ وإعادة شحن بالوزن'}},
      {title:{en:'Overcharged',ar:'شحن زائد'},sym:{en:'High both pressures, compressor laboring, poor cooling, liquid line very warm',ar:'ضغط عالي في الجانبين، الضاغط يعمل بجهد، تبريد ضعيف، خط سائل دافئ جداً'},cause:{en:'Too much refrigerant added, often from DIY cans',ar:'تم إضافة مبرد كثير، غالباً من عبوات DIY'},fix:{en:'Recover excess refrigerant with recovery machine, do not vent, charge to spec by weight',ar:'استرد المبرد الزائد بجهاز استرداد، لا تفرّغ، اشحن بالوزن'}},
      {title:{en:'Wrong Refrigerant',ar:'مبرد خاطئ'},sym:{en:'Abnormal pressures, poor performance, oil contamination',ar:'ضغوط غير طبيعية، أداء ضعيف، تلوث زيت'},cause:{en:'Cross-contamination from shared equipment or wrong can',ar:'تلوث متبادل من معدات مشتركة أو عبوة خاطئة'},fix:{en:'Full system recovery, flush, replace drier, recharge with correct refrigerant',ar:'استرداد كامل للنظام، غسل، استبدل المجفف، أعد الشحن بالمبرد الصحيح'}}
    ],
    pressure: [
      {title:{en:'Low Suction + High Discharge',ar:'مصعد منخفض + تفريغ عالي'},sym:{en:'Low suction, high head, poor cooling, warm liquid line',ar:'مصعد منخفض، تفريغ عالي، تبريد ضعيف، خط سائل دافئ'},cause:{en:'Restriction in expansion valve, clogged orifice tube, or kinked liquid line',ar:'انسداد في صمام التمديد، أنبوب مسدود، أو خط سائل مثني'},fix:{en:'Check/replace orifice tube or TXV, check for kinks, flush system',ar:'افحص/استبدل أنبوب الفتحة أو TXV، افحص الثنيات، اغسل النظام'}},
      {title:{en:'High Suction + Low Discharge',ar:'مصعد عالي + تفريغ منخفض'},sym:{en:'High suction, low head, warm air from vents',ar:'مصعد عالي، تفريغ منخفض، هواء دافئ من الفتحات'},cause:{en:'Compressor valve failure (worn reed valves), compressor not pumping efficiently',ar:'عطل صمامات الضاغط (صمامات ريد مرتخية)، ضاغط لا يضخ بكفاءة'},fix:{en:'Replace compressor, flush system, replace accumulator',ar:'استبدل الضاغط، اغسل النظام، استبدل المُجمّع'}},
      {title:{en:'Equalized Pressures (System Off Won\'t Start)',ar:'ضغوط متساوية (النظام مغلق لن يبدأ)'},sym:{en:'High and low side equalize quickly after shutoff',ar:'الجانبان يتساويان بسرعة بعد الإيقاف'},cause:{en:'Leaking compressor valves or stuck-open TXV',ar:'صمامات ضاغط تالفة أو TXV مفتوح'},fix:{en:'Check compressor valve integrity, replace TXV if stuck',ar:'افحص سلامة صمامات الضاغط، استبدل TXV إذا عالق'}}
    ],
    electrical: [
      {title:{en:'Compressor Won\'t Engage',ar:'الضاغط لا يعمل'},sym:{en:'No click from compressor clutch, blows warm air',ar:'لا صوت من مخلّفة الضاغط، يهب هواء دافئ'},cause:{en:'Low pressure switch tripped (<20 PSIG), bad clutch coil, blown fuse, or bad relay',ar:'مفتاح ضغط منخفض قاطع (<20 PSIG)، ملف مخلّفة خربان، فيوز محترق، أو ريلاي خربان'},fix:{en:'Check refrigerant pressure first, then check clutch coil resistance (3-5 ohms), check fuses and relays',ar:'افحص ضغط المبرد أولاً، ثم افحص مقاومة ملف المخلّفة (3-5 أوم)، افحص الفيوزات والريلايات'}},
      {title:{en:'Compressor Short Cycling',ar:'قطع متكرر للضاغط'},sym:{en:'Compressor clicks on/off every few seconds',ar:'الضاغط يعمل/يتوقف كل ثوانٍ'},cause:{en:'Low charge, overcharge, bad pressure switch, or failing clutch',ar:'شحن منخفض، شحن زائد، مفتاح ضغط خربان، أو مخلّفة تالفة'},fix:{en:'Check charge level, check pressure switch, check clutch air gap (0.3-0.6mm)',ar:'افحص مستوى الشحن، افحص مفتاح الضغط، افحص فجوة المخلّفة (0.3-0.6mm)'}},
      {title:{en:'AC Blower Not Working',ar:'ناشر المكيف لا يعمل'},sym:{en:'No air from vents, compressor runs but no cooling effect',ar:'لا هواء من الفتحات، الضاغط يعمل لكن لا تبريد'},cause:{en:'Blower motor fuse, blown resistor pack, or failed motor',ar:'فيوز محرك الناشر، حزمة مقاومة محترقة، أو محرك معطّل'},fix:{en:'Check fuse, check resistor pack, check motor with direct 12V test',ar:'افحص الفيوز، افحص حزمة المقاومة، افحص المحرك بـ 12V مباشرة'}}
    ]
  },
  r22: {
    charging: [
      {title:{en:'Low Charge',ar:'شحن منخفض'},sym:{en:'Warm supply air, low suction, high superheat, frost on suction line at compressor',ar:'هواء توريد دافئ، مصعد منخفض، سوبريتي عالي، صقيع على خط الشفط عند الضاغط'},cause:{en:'Leak at flare fittings, service valves, evaporator coil, or Schrader cores',ar:'تسريب عند وصلات الشعلة أو صمامات الخدمة أو ملف المبخر أو أنابيب شريدر'},fix:{en:'Nitrogen pressure test, soap bubbles on joints, repair leak, evacuate 500 microns, recharge by weight',ar:'اختبار ضغط بالنيتروجين، فقاعات صابون على الوصلات، إصلاح التسريب، تفريغ 500 ميكرون، إعادة شحن بالوزن'}},
      {title:{en:'Overcharged',ar:'شحن زائد'},sym:{en:'High head pressure, high subcooling, liquid line warm, compressor noisy',ar:'ضغط تفريغ عالي، تبريد تحت تشبع عالي، خط سائل دافئ، ضاغط ضوضائي'},cause:{en:'Added too much R-22 during previous service',ar:'تم إضافة R-22 كثير أثناء صيانة سابقة'},fix:{en:'Recover excess with recovery unit, R-22 is expensive — save recovered refrigerant',ar:'استرد الزائد بجهاز استرداد، R-22 مكلف — وفّر المبرد المسترد'}},
      {title:{en:'R-22 Shortage (No New Supply)',ar:'نقص R-22 (لا يوجد مورّد جديد)'},sym:{en:'Cannot find R-22 to recharge',ar:'لا يمكن العثور على R-22 لإعادة الشحن'},cause:{en:'Production banned since 2020, only reclaimed available',ar:'الإنتاج محظور منذ 2020، فقط المسترد متاح'},fix:{en:'Consider retrofit to R-407C or R-438A (MO99), consult manufacturer specs',ar:'فكّر في التحويل إلى R-407C أو R-438A (MO99)، راجع مواصفات الشركة'}}
    ],
    pressure: [
      {title:{en:'Low Suction + High Head',ar:'مصعد منخفض + تفريغ عالي'},sym:{en:'Evaporator starving, condenser flooding, poor cooling',ar:'المبخر يتضور جوعاً، المكثف يفيض، تبريد ضعيف'},cause:{en:'Liquid line restriction, clogged filter drier, or TXV stuck partially closed',ar:'انسداد في خط السائل، فلتر مجفف مسدود، أو TXV عالق نصف مغلق'},fix:{en:'Replace filter drier, check TXV sensing bulb location and charge, check for kinks',ar:'استبدل فلتر المجفف، افحص موقع مستشعر TXV وشحنه، افحص الثنيات'}},
      {title:{en:'High Suction + Low Head',ar:'مصعد عالي + تفريغ منخفض'},sym:{en:'Warm air, poor dehumidification, compressor running continuously',ar:'هواء دافئ، إزالة رطوبة ضعيفة، الضاغط يعمل باستمرار'},cause:{en:'Compressor wear, bad valves, or TXV stuck open',ar:'تآكل الضاغط، صمامات تالفة، أو TXV عالق مفتوح'},fix:{en:'Check compressor amperage vs RLA, replace if underperforming, check TXV',ar:'افحص تيار الضاغط مقابل RLA، استبدل إذا كان ضعيفاً، افحص TXV'}},
      {title:{en:'Low Both Pressures',ar:'كلا الضغطين منخفضين'},sym:{en:'Low suction AND low head, ice on evaporator',ar:'مصعد منخفض AND تفريغ منخفض، جليد على المبخر'},cause:{en:'Severe undercharge or restricted airflow (dirty filter/coil)',ar:'شحن منخفض حاد أو تدفق هواء محدود (فلتر/ملف متسخ)'},fix:{en:'Check air filter and coil first, then check charge, look for visible ice',ar:'افحص فلتر الهواء والملف أولاً، ثم افحص الشحن، ابحث عن جليد مرئي'}}
    ],
    electrical: [
      {title:{en:'Contactor Not Pulling In',ar:'الكونتاكتور لا ينجذب'},sym:{en:'Outdoor unit fan and compressor not running',ar:'الوحدة الخارجية (مروحة وضاغط) لا تعمل'},cause:{en:'Bad thermostat signal, failed contactor coil, or safety lockout',ar:'إشارة ثرموستات خاطئة، ملف كونتاكتور معطّل، أو قفل أمان'},fix:{en:'Check 24V at contactor coil, check capacitor, check for safety lockouts (HP/LP/overload)',ar:'افحص 24V عند ملف الكونتاكتور، افحص المكثف، افحص أقفال الأمان (HP/LP/overload)'}},
      {title:{en:'Compressor Overheating',ar:'الضاغط يسخن'},sym:{en:'Compressor shuts off on thermal overload after running',ar:'الضاغط ينقطع على الحمل الحراري بعد التشغيل'},cause:{en:'Dirty condenser, low charge, high ambient, or failing compressor',ar:'مكثف متسخ، شحن منخفض، محيط حار، أو ضاغط يفشل'},fix:{en:'Clean condenser, check charge, check amp draw vs RLA, check ventilation around unit',ar:'نظّف المكثف، افحص الشحن، افحص التيار مقابل RLA، افحص التهوية حول الوحدة'}},
      {title:{en:'Capacitor Failure',ar:'عطل مكثف'},sym:{en:'Compressor hums but won\'t start, or runs hot',ar:'الضاغط يطن لكن لا يبدأ، أو يعمل ساخناً'},cause:{en:'Run capacitor degraded from heat age',ar:'مكثف التشغيل تدهور من الحرارة والعمر'},fix:{en:'Test capacitor with multimeter (should be within 6% of rated MFD), replace if weak',ar:'افحص المكثف بالملتيميتر (يجب أن يكون ضمن 6% من MFD المُقيّم)، استبدل إذا ضعيف'}}
    ]
  },
  r410a: {
    charging: [
      {title:{en:'Low Charge',ar:'شحن منخفض'},sym:{en:'Low suction, poor cooling, coil frosting, high superheat',ar:'مصعد منخفض، تبريد ضعيف، تجفيف الملف، سوبريتي عالي'},cause:{en:'Leak at braze joints, flare connections, service caps, or coil',ar:'تسريب عند وصلات اللحام أو وصلات الشعلة أو أغطية الخدمة أو الملف'},fix:{en:'Electronic leak detector or nitrogen test with bubbles, repair, evacuate to 500 microns, recharge by weight with liquid charge',ar:'كاشف تسريب إلكتروني أو اختبار نيتروجين بالفقاعات، إصلاح، تفريغ لـ 500 ميكرون، إعادة شحن بالوزن بالسائل'}},
      {title:{en:'Overcharged',ar:'شحن زائد'},sym:{en:'Very high head pressure (can exceed 600 PSIG), noisy compressor, poor efficiency',ar:'ضغط تفريغ عالي جداً (يمكن أن يتجاوز 600 PSIG)، ضاغط ضوضائي، كفاءة منخفضة'},cause:{en:'Charged by pressure alone in cool weather, or added too much',ar:'شُحن بالضغط وحده في الطقس البارد، أو أُضيف كثير'},fix:{en:'Recover excess — do NOT vent (illegal and dangerous at these pressures), charge by weight',ar:'استرد الزائد — لا تفرّغ (غير قانوني وخطير بهذه الضغوط)، اشحن بالوزن'}},
      {title:{en:'Mixed Refrigerant',ar:'مزيج مبردات'},sym:{en:'Abnormal pressures, poor performance, possible compressor damage',ar:'ضغوط غير طبيعية، أداء ضعيف، تلف محتمل للضاغط'},cause:{en:'Used R-22 gauges without proper flushing, or wrong cylinder',ar:'استخدم مانوميتر R-22 بدون غسل مناسب، أو أسطوانة خاطئة'},fix:{en:'Full recovery, system flush, replace filter drier, recharge with virgin R-410A',ar:'استرداد كامل، غسل النظام، استبدل فلتر المجفف، أعد الشحن بـ R-410A نقي'}}
    ],
    pressure: [
      {title:{en:'Low Suction + Very High Head',ar:'مصعد منخفض + تفريغ عالي جداً'},sym:{en:'Evaporator starving, head >500 PSIG at 95°F, compressor hot',ar:'المبخر يتضور جوعاً، تفريغ >500 PSIG عند 95°F، ضاغط ساخن'},cause:{en:'Restriction — clogged filter drier, ice in liquid line (moisture), kinked line',ar:'انسداد — فلتر مجفف مسدود، جليد في خط السائل (رطوبة)، خط مثني'},fix:{en:'Replace filter drier, check for moisture with sight glass, look for kinks',ar:'استبدل فلتر المجفف، افحص الرطوبة بنافذة رؤية، ابحث عن ثنيات'}},
      {title:{en:'High Suction + Low Head',ar:'مصعد عالي + تفريغ منخفض'},sym:{en:'Poor cooling, compressor running continuously, warm air',ar:'تبريد ضعيف، ضاغط يعمل باستمرار، هواء دافئ'},cause:{en:'Compressor valve failure or TXV stuck open (unlikely with EEV)',ar:'عطل صمامات الضاغط أو TXV عالق مفتوح (غير مرجح مع EEV)'},fix:{en:'Check compressor amp draw, check TXV operation, replace compressor if valves failed',ar:'افحص تيار الضاغط، افحص تشغيل TXV، استبدل الضاغط إذا الصمامات تالفة'}},
      {title:{en:'Head Pressure Too High (>600 PSIG)',ar:'ضغط تفريغ عالي جداً (>600 PSIG)'},sym:{en:'Compressor may trip on high pressure safety, very hot discharge line',ar:'الضاغط قد يقطع على أمان ضغط عالي، خط تفريغ ساخن جداً'},cause:{en:'Dirty condenser, non-condensables (air) in system, fan motor failure, or overcharge',ar:'مكثف متسخ، غازات غير متكاثفة (هواء) في النظام، عطل مروحة، أو شحن زائد'},fix:{en:'Clean condenser, check fan motor, if air in system — full recovery and evacuate',ar:'نظّف المكثف، افحص مروحة، إذا هواء في النظام — استرداد كامل وتفريغ'}}
    ],
    electrical: [
      {title:{en:'Compressor Won\'t Start',ar:'الضاغط لا يبدأ'},sym:{en:'No operation, possible error code on board',ar:'لا تشغيل، رمز خطأ محتمل على اللوحة'},cause:{en:'Low pressure switch, bad board, bad capacitor, or locked rotor',ar:'مفتاح ضغط منخفض، لوحة معطّلة، مكثف معطّل، أو روتور مغلق'},fix:{en:'Check pressure, check error codes, capacitor test, check LRA vs nameplate',ar:'افحص الضغط، افحص رموز الخطأ، اختبار المكثف، افحص LRA مقابل اللوحة'}},
      {title:{en:'Inverter Compressor Fault',ar:'عطل ضاغط الإنفرتر'},sym:{en:'Unit runs briefly then shuts down with fault code',ar:'الوحدة تعمل لفترة قصيرة ثم تتوقف مع رمز خطأ'},cause:{en:'DC bus voltage issue, IPM module failure, or refrigerant charge issue',ar:'مشكلة جهد DC bus، عطل وحدة IPM، أو مشكلة شحن مبرد'},fix:{en:'Read error code from board, check charge level, may need board replacement',ar:'اقرأ رمز الخطأ من اللوحة، افحص مستوى الشحن، قد تحتاج استبدال لوحة'}},
      {title:{en:'EEV (Electronic Expansion Valve) Fault',ar:'عطل صمام التمديد الإلكتروني (EEV)'},sym:{en:'Poor superheat control, fluctuating pressures, possible freeze-up',ar:'تحكم ضعيف في السوبريتي، ضغوط متذبذبة، تجمد محتمل'},cause:{en:'Stepper motor failure, connector loose, or board signal issue',ar:'عطل محرك خطوات، وصلة مرتخية، أو مشكلة إشارة اللوحة'},fix:{en:'Check EEV connector, manually test valve movement via service mode, replace if stuck',ar:'افحص وصلة EEV، اختبر حركة الصمام يدوياً عبر وضع الخدمة، استبدل إذا عالق'}}
    ]
  },
  r32: {
    charging: [
      {title:{en:'Low Charge',ar:'شحن منخفض'},sym:{en:'Low suction, poor cooling, high superheat, frost on suction line',ar:'مصعد منخفض، تبريد ضعيف، سوبريتي عالي، صقيع على خط الشفط'},cause:{en:'Leak at flare connections, braze joints, or service ports',ar:'تسريب عند وصلات الشعلة أو اللحام أو منافذ الخدمة'},fix:{en:'Leak test with A2L-rated detector, repair, evacuate to 500 microns, recharge by weight',ar:'اختبار تسريب بكاشف مُصنّف لـ A2L، إصلاح، تفريغ لـ 500 ميكرون، إعادة شحن بالوزن'}},
      {title:{en:'Overcharged',ar:'شحن زائد'},sym:{en:'High head pressure, poor efficiency, possible high-pressure cutout',ar:'ضغط تفريغ عالي، كفاءة منخفضة، قطع ضغط عالي محتمل'},cause:{en:'Charged incorrectly or added too much',ar:'شُحن بشكل خاطئ أو أُضيف كثير'},fix:{en:'Recover excess refrigerant, charge by weight per nameplate',ar:'استرد المبرد الزائد، اشحن بالوزن حسب اللوحة'}},
      {title:{en:'A2L Safety Concern During Charging',ar:'مخاوف سلامة A2L أثناء الشحن'},sym:{en:'N/A — safety procedure issue',ar:'لا ينطبق — مشكلة إجراء سلامة'},cause:{en:'Charging near ignition source or in enclosed space without ventilation',ar:'الشحن بالقرب من مصدر اشتعال أو في مغلق بدون تهوية'},fix:{en:'Always ensure ventilation, keep ignition sources away, use A2L-rated equipment',ar:'تأكد دائماً من التهوية، أبعد مصادر الاشتعال، استخدم معدات مُصنّفة لـ A2L'}}
    ],
    pressure: [
      {title:{en:'Low Suction + High Head',ar:'مصعد منخفض + تفريغ عالي'},sym:{en:'Poor cooling, discharge line very hot',ar:'تبريد ضعيف، خط تفريغ ساخن جداً'},cause:{en:'Restriction in liquid line, clogged filter drier, or TXV issue',ar:'انسداد في خط السائل، فلتر مجفف مسدود، أو مشكلة TXV'},fix:{en:'Check/replace filter drier, inspect TXV sensing bulb, check for kinks',ar:'افحص/استبدل فلتر المجفف، افحص مستشعر TXV، افحص الثنيات'}},
      {title:{en:'High Suction + Low Head',ar:'مصعد عالي + تفريغ منخفض'},sym:{en:'Warm air, poor cooling, compressor running constantly',ar:'هواء دافئ، تبريد ضعيف، ضاغط يعمل باستمرار'},cause:{en:'Compressor valve failure or metering device stuck open',ar:'عطل صمامات الضاغط أو جهاز قياس عالق مفتوح'},fix:{en:'Check compressor amps vs RLA, check metering device operation',ar:'افحص تيار الضاغط مقابل RLA، افحص تشغيل جهاز القياس'}},
      {title:{en:'Head Pressure Extremely High',ar:'ضغط تفريغ مرتفع للغاية'},sym:{en:'Compressor trips on high pressure, very hot discharge',ar:'الضاغط يقطع على ضغط عالي، تفريغ ساخن جداً'},cause:{en:'Dirty condenser, fan failure, non-condensables in system, or overcharge',ar:'مكثف متسخ، عطل مروحة، غازات غير متكاثفة في النظام، أو شحن زائد'},fix:{en:'Clean condenser, check fan, if non-condensables — full recovery and evacuate',ar:'نظّف المكثف، افحص المروحة، إذا غازات غير متكاثفة — استرداد كامل وتفريغ'}}
    ],
    electrical: [
      {title:{en:'Compressor Won\'t Start',ar:'الضاغط لا يبدأ'},sym:{en:'No operation or error code on display',ar:'لا تشغيل أو رمز خطأ على الشاشة'},cause:{en:'Safety switch tripped, bad inverter board, or capacitor failure',ar:'مفتاح أمان قاطع، لوحة إنفرتر معطّلة، أو عطل مكثف'},fix:{en:'Check pressures and safety switches, read error codes, test capacitor',ar:'افحص الضغوط ومفاتيح الأمان، اقرأ رموز الخطأ، اختبر المكثف'}},
      {title:{en:'A2L Leak Detection System Alarm',ar:'إنذار نظام كشف تسريب A2L'},sym:{en:'Unit locked out, flashing error code',ar:'الوحدة قُفلت، رمز خطأ يومض'},cause:{en:'Refrigerant leak detected by built-in sensor, or sensor malfunction',ar:'تم كشف تسريب مبرد بالمستشعر المدمج، أو عطل في المستشعر'},fix:{en:'Ventilate area, check for actual leak with detector, reset after clearing, replace sensor if faulty',ar:'هوّئ المنطقة، افحص التسريب الفعلي بالكاشف، أعد التعيين بعد المسح، استبدل المستشعر إذا معطّل'}},
      {title:{en:'Inverter Board Fault',ar:'عطل لوحة الإنفرتر'},sym:{en:'Unit starts then stops with fault code, compressor ramps erratically',ar:'الوحدة تبدأ ثم تتوقف مع رمز خطأ، الضاغط يعمل بشكل متسارع'},cause:{en:'Board failure, power supply issue, or compressor winding fault',ar:'عطل لوحة، مشكلة مزود طاقة، أو عطل لفافات الضاغط'},fix:{en:'Read error code, check power supply, check compressor winding resistance, may need board replacement',ar:'اقرأ رمز الخطأ، افحص مزود الطاقة، افحص مقاومة لفافات الضاغط، قد تحتاج استبدال لوحة'}}
    ]
  }
};

// Oil diagnostics data (shared across all refrigerants)
window.OIL_DIAGNOSTICS = {
  colors: [
    {color:{en:'Clear / Pale Yellow',ar:'صافٍ / أصفر فاتح'},bg:'#f0f0a0',status:{en:'✅ Good',ar:'✅ جيد'},desc:{en:'Pure, uncontaminated oil. No action needed.',ar:'زيت نقي، غير ملوّث. لا حاجة لإجراء.'},action:{en:'None — oil is healthy',ar:'لا شيء — الزيت سليم'}},
    {color:{en:'Light Orange / Dark Yellow',ar:'برتقالي فاتح / أصفر غامق'},bg:'#e8c060',status:{en:'⚠️ Monitor',ar:'⚠️ راقب'},desc:{en:'Slight moisture presence. Oil viscosity unaffected.',ar:'رطوبة طفيفة. لزوجة الزيت لم تتأثر.'},action:{en:'Check for leaks, monitor filter drier, check sight glass',ar:'افحص التسريبات، راقب فلتر المجفف، افحص نافذة الرؤية'}},
    {color:{en:'Amber / Honey',ar:'كهرماني / عسلي'},bg:'#c8960a',status:{en:'⚠️ Attention',ar:'⚠️ انتبه'},desc:{en:'Moderate moisture or early oxidation. Oil still functional.',ar:'رطوبة متوسطة أو بداية تأكسد. الزيت لا يزال يعمل.'},action:{en:'Change filter drier, monitor oil condition, consider oil sample test',ar:'استبدل فلتر المجفف، راقب حالة الزيت، فكّر في اختبار عينة زيت'}},
    {color:{en:'Brown / Dark Brown',ar:'بني / بني غامق'},bg:'#8b4513',status:{en:'🔴 Replace',ar:'🔴 استبدل'},desc:{en:'Contaminated — burnt oil, acid, moisture. Viscosity severely affected.',ar:'ملوث — زيت محترق، حمض، رطوبة. لزوجة متأثرة بشدة.'},action:{en:'Replace oil, flush system, replace filter drier, check compressor',ar:'استبدل الزيت، اغسل النظام، استبدل فلتر المجفف، افحص الضاغط'}},
    {color:{en:'Black',ar:'أسود'},bg:'#1a1a1a',status:{en:'🔴 BURNOUT',ar:'🔴 احتراق'},desc:{en:'Severe high-temp operation. Black sludge, acid, metals in solution. Compressor likely failed.',ar:'تشغيل شديد الحرارة. حمأة سوداء، حمض، معادن في المحلول. الضاغط على الأرجح معطّل.'},action:{en:'Full system flush, replace compressor, replace filter drier, multiple evacuations',ar:'غسل كامل للنظام، استبدل الضاغط، استبدل فلتر المجفف، تفريغات متعددة'}},
    {color:{en:'Green Slime',ar:'أخضر لزج'},bg:'#2d8b2d',status:{en:'🔴 Contaminated',ar:'🔴 ملوّث'},desc:{en:'Copper contamination from moisture + high temp attacking copper tubing.',ar:'تلوث نحاسي من رطوبة + حرارة عالية تهاجم أنابيب النحاس.'},action:{en:'Flush system, replace oil, check for moisture source, replace filter drier',ar:'اغسل النظام، استبدل الزيت، افحص مصدر الرطوبة، استبدل فلتر المجفف'}},
    {color:{en:'Red / Pink',ar:'أحمر / وردي'},bg:'#c04040',status:{en:'🔴 Contaminated',ar:'🔴 ملوّث'},desc:{en:'Acid + moisture reacting with anti-wear additives (phosphorus). Rubber hose degradation.',ar:'حمض + رطوبة يتفاعل مع مضادات التآكل (فوسفور). تدهور خراطيم المطاط.'},action:{en:'Flush system, replace oil, check hoses, replace filter drier, acid test',ar:'اغسل النظام، استبدل الزيت، افحص الخراطيم، استبدل فلتر المجفف، اختبار حمض'}}
  ],
  smells: [
    {smell:{en:'No Smell (or slight oil smell)',ar:'لا رائحة (أو رائحة زيت خفيفة)'},status:{en:'✅ Normal',ar:'✅ طبيعي'},desc:{en:'Oil is in good condition',ar:'الزيت في حالة جيدة'}},
    {smell:{en:'Slight Burnt Smell',ar:'رائحة حرق خفيفة'},status:{en:'⚠️ Warning',ar:'⚠️ تحذير'},desc:{en:'Mild overheating has occurred. Check compressor temperature and ventilation',ar:'حدث تجاوز حراري خفيف. افحص حرارة الضاغط والتهوية'}},
    {smell:{en:'Strong Burnt / Acrid',ar:'رائحة حرق قوية / لاذعة'},status:{en:'🔴 Critical',ar:'🔴 حرج'},desc:{en:'Compressor overheating or burnout. Oil breakdown and acid likely present',ar:'الضاغط يسخن أو احترق. تدهور زيت وحمض على الأرجح'}},
    {smell:{en:'Acidic / Sharp Chemical',ar:'حمضي / كيميائي حاد'},status:{en:'🔴 Acid',ar:'🔴 حمض'},desc:{en:'Acid contamination confirmed. System needs flush and oil replacement',ar:'تلوث حمضي مؤكّد. النظام يحتاج غسل واستبدال زيت'}},
    {smell:{en:'Musty / Moldy',ar:'عفن / رطب'},status:{en:'⚠️ Moisture',ar:'⚠️ رطوبة'},desc:{en:'Moisture contamination. Check filter drier and system seals',ar:'تلوث برطوبة. افحص فلتر المجفف وأختام النظام'}}
  ]
};

// Compressor types reference data
window.COMPRESSOR_TYPES = [
  {type:'Scroll',range:'1.5–30 Ton',pros:{en:'Quiet, efficient, high reliability, few moving parts',ar:'هادئ، كفاءة عالية، موثوقية عالية، قطع متحركة قليلة'},cons:{en:'Cannot be repaired (replace only), higher cost',ar:'لا يمكن إصلاحه (استبدال فقط)، تكلفة أعلى'},common:{en:'Modern residential, commercial rooftop, heat pumps',ar:'سكني حديث، أسطح تجارية، مضخات حرارة'}},
  {type:'Reciprocating',range:'0.5–50 Ton',pros:{en:'Proven technology, repairable, good at part load',ar:'تقنية مُجرّبة، قابل للإصلاح، جيد في الحمل الجزئي'},cons:{en:'More moving parts, noisier, vibration, lower efficiency',ar:'قطع متحركة أكثر، أكثر ضوضاء، اهتزاز، كفاءة أقل'},common:{en:'Legacy residential, small commercial, refrigeration',ar:'سكني قديم، تجاري صغير، تبريد'}},
  {type:'Rotary',range:'0.5–4 Ton',pros:{en:'Compact, smooth operation, good for inverter drives',ar:'مدمج، تشغيل سلس، جيد لمحركات الإنفرتر'},cons:{en:'Limited capacity range, sealed (not repairable)',ar:'نطاق قدرة محدود، مختوم (غير قابل للإصلاح)'},common:{en:'Mini-splits, window units, portable AC',ar:'ميني سبليت، وحدات شباك، مكيف محمول'}},
  {type:'Screw',range:'20–1000+ Ton',pros:{en:'Very high capacity, unloading to 25%, efficient',ar:'قدرة عالية جداً، تفريغ حتى 25%، كفاءة'},cons:{en:'Expensive, complex, oil management critical',ar:'مكلف، معقد، إدارة الزيت حرجة'},common:{en:'Large commercial, industrial, chillers',ar:'تجاري كبير، صناعي، مبردات'}},
  {type:'Centrifugal',range:'100–10000+ Ton',pros:{en:'Highest capacity, very efficient at full load',ar:'أعلى قدرة، كفاءة عالية عند الحمل الكامل'},cons:{en:'Very expensive, surge risk, limited turndown',ar:'مكلف جداً، خطر ارتداد، تحويل محدود'},common:{en:'Large commercial, industrial, process cooling',ar:'تجاري كبير، صناعي، تبريد عملي'}}
];

// Amperage reference table
window.AMPERAGE_REF = [
  {cap:'9,000 BTU (0.75T)',rla:'3–5A',lra:'15–25A',moc:'8A',wire:'14 AWG',breaker:'15A'},
  {cap:'12,000 BTU (1T)',rla:'5–8A',lra:'25–35A',moc:'12A',wire:'14 AWG',breaker:'15A'},
  {cap:'18,000 BTU (1.5T)',rla:'7–10A',lra:'30–45A',moc:'15A',wire:'12 AWG',breaker:'20A'},
  {cap:'24,000 BTU (2T)',rla:'10–14A',lra:'40–60A',moc:'20A',wire:'12 AWG',breaker:'25A'},
  {cap:'30,000 BTU (2.5T)',rla:'12–16A',lra:'50–70A',moc:'25A',wire:'10 AWG',breaker:'30A'},
  {cap:'36,000 BTU (3T)',rla:'14–20A',lra:'60–80A',moc:'30A',wire:'10 AWG',breaker:'35A'},
  {cap:'42,000 BTU (3.5T)',rla:'16–22A',lra:'65–90A',moc:'35A',wire:'8 AWG',breaker:'40A'},
  {cap:'48,000 BTU (4T)',rla:'18–26A',lra:'75–100A',moc:'40A',wire:'8 AWG',breaker:'45A'},
  {cap:'60,000 BTU (5T)',rla:'24–35A',lra:'90–130A',moc:'50A',wire:'6 AWG',breaker:'50A'}
];